name: Complexity level 7 -> Run Tests

on:
  # schedule:
    # - cron: "0 8 * * *" # run on schedule, examples: https://crontab.guru/examples.html
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment: staging / dev"
        required: true
        options:                  
          - dev -> flowmap-dev.fly.dev
          - staging -> flowmap-staging.fly.dev
          - prod -> app.flowmap.com
        default: "staging"
      test_type:
        type: choice
        description: "Select type of tests to run"
        required: true
        options:
          - e2e
          - smoke
          - regression
          - editor
          - login
          - create new flow
          - actions
          - roles
          - chatgpt
        default: "e2e"

jobs:
  list-specs:
    name: Files
    uses: "./.github/workflows/cy-list-of-specs.yml"

  build-packages:
    name: Build
    uses: "./.github/workflows/cy-build-packages.yml"

  run-specs:
    name: Run
    needs: [list-specs, build-packages]
    if: always()
    uses: "./.github/workflows/cy-run-specs.yml"
    with:
      specs: ${{ needs.list-specs.outputs.specs }}

  report:
    name: Report
    needs: run-specs
    if: always()
    uses: "./.github/workflows/cy-slack-reporting.yml"
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    with:
      tests-result: ${{ needs.run-specs.result }}
      environment: ${{ inputs.environment }}
