name: Complexity level 2 -> Run Tests

on: push

jobs:
  run-specs:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ">=16.0.0"

      - name: Run Tests on already hosted app
        uses: cypress-io/github-action@v6
        with:
          install: true
          browser: chrome
          config-file: /${{ github.workspace }}/cypress/configs/cypress.dev.config.js

      - name: Cypress screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: ${{ github.workspace }}/cypress/screenshots

      - name: Cypress videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: ${{ github.workspace }}/cypress/videos

      - name: Logs from the run
        if: always()
        run: |
          echo "--<< BRANCH_NAME >>--"
          export BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "--<< GITHUB ACTION RUN URL >>--"
          export RUN_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          echo "--<< WORKFLOW TRIGGER EVENT NAME >>--"
          echo ${{ github.event_name }}
