name: Complexity level 1 -> Run Tests

on: push

jobs:
  run-specs:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ">=16.0.0"

      - name: Run Tests on already hosted app
        uses: cypress-io/github-action@v6
        with:
          install: true
          browser: chrome
          config-file: /${{ github.workspace }}/cypress/configs/cypress.dev.config.js

      - name: Logs from the run
        if: always()
        run: |
          echo "--<< BRANCH NAME >>--"
          echo ${GITHUB_REF#refs/heads/}
          echo "--<< TEST RUN URL >>--"
          echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          echo "--<< WORKFLOW TRIGGER EVENT >>--"
          echo ${{ github.event_name }}
          echo "--<< ALL FILES UNDER WORKSPACE >>--"
          ls -lh ${{ github.workspace }}
